language: cpp
dist: precise
comiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:libreoffice/ppa
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-4.7 gfortran openmpi-bin openmpi-common openmpi-dev libnetcdf6 libnetcdf-dev libnuma1 libnuma-dev cmake doxygen graphviz texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-font-utils
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
 - sudo update-alternatives --set gcc /usr/bin/gcc-4.7

env:
 global:
   secure: "ZBhx5ai3VyZ223k5WEAVkC9Av1IqmHpyd4leKkMUrRc7ht2Zy4E3qus+Po3Y0XvwjAfeuR4ObFh69W5rZyq0YSfRCKSNianeBvalZ1mZQ5siOv37rf2OIweuRMjXwPrjXS40ctPamog9rK2/CmXb5jkQ2A08sr32dx3fiIU/gZk="

branches:
 except:
  - gh-pages

script:
 - mkdir build && cd build && cmake ../ -DTESTS=ON -DMPI3=OFF
 - make
 - make test
 - make doc
 - make devdoc
 - cd ..
 - mkdir build_numa && cd build_numa && cmake ../ -DTESTS=ON -DDEBUG_NUMA=ON -DMPI3=OFF
 - make
 - make test
 - cd ..
 - mkdir build_nonuma && cd build_nonuma && cmake ../ -DTESTS=ON -DNONUMA=ON -DMPI3=OFF
 - make
 - make test
 - cd ..
 - mkdir build_nompi && cd build_nompi && cmake ../ -DTESTS=ON -DNOMPI=ON -DDEBUG_NUMA=ON
 - make
 - make test
 - cd ..
 - mkdir build_numa_nompi && cd build_numa && cmake ../ -DTESTS=ON -DNONUMA=ON -DMPI3=OFF
 - make
 - make test
 - cd ..
 - mkdir build_nonuma_nompi && cd build_nonuma_nompi && cmake ../ -DTESTS=ON -DNONUMA=ON -DNOMPI=ON
 - make
 - make test
 - cd ..

after_success:
 - documentation/gh_pages.sh
